### ISSUE TITLE
Update `sckan-version` in manifest. 

### ISSUE THREAD

**Issue by dbrnz** [AnatomicMaps/vagus-nerve-flatmap#2]
FYI @hsorby the `sckan-version` field now needs to specify an exact SCKAN release, for example:
```
"sckan-version": "sckan-2024-03-26",
```

There is also no need to specify the empty  `anatomicalMap`, `connectivityTerms`, and `neuronConnectivity` fields.

**Comment by hsorby** [comment]
Thanks.

**Comment by dbrnz** [comment]
Fixed as part of commit b9465c4.
